# Generated by Django 5.2.4 on 2025-08-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='referal_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('Linkdin_URL', models.URLField()),
                ('Github_URL', models.URLField()),
                ('Bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('your_role', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('mail_id', models.EmailField(max_length=100)),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField()),
                ('bio', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
