# Generated by Django 5.1.7 on 2025-08-05 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_referal_req_referee_delete_fruit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Referee',
            new_name='Referer',
        ),
    ]
