# Generated by Django 5.1.7 on 2025-08-18 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_user_managers_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('Refferal_Domains', models.CharField(max_length=100)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
