# Generated by Django 5.1.7 on 2025-08-18 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_referral_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
