# Generated by Django 5.1.7 on 2025-08-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_referral_post_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100000)),
                ('position', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=10000)),
            ],
        ),
    ]
