# Generated by Django 5.1.7 on 2025-08-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.CharField(default='Not disclosed', max_length=100),
        ),
    ]
