# Generated by Django 5.1.7 on 2025-08-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_jobs_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(default='Remote', max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('salary', models.CharField(blank=True, default='Not disclosed', max_length=255)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_source_external'),
        ),
    ]
