# Generated by Django 5.1.7 on 2025-09-18 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_job_delete_jobs_job_uniq_source_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral_post',
            name='user',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='referral_posts_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral_post',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_posts_referrer', to=settings.AUTH_USER_MODEL),
        ),
    ]
