# Generated by Django 5.1.7 on 2025-09-24 04:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_referral_post_user_alter_referral_post_referrer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral_post',
            old_name='Refferal_Domains',
            new_name='experience_required',
        ),
        migrations.RenameField(
            model_name='referral_post',
            old_name='Role',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='referral_post',
            name='referrer',
        ),
        migrations.AddField(
            model_name='referral_post',
            name='availability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referral_post',
            name='job_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral_post',
            name='link_to_apply',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral_post',
            name='referral_domains',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral_post',
            name='role',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral_post',
            name='salary_expectation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referral_post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
