# Generated by Django 5.1.7 on 2025-09-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_refferal_domains_referral_post_experience_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral_post',
            name='referral_domains',
            field=models.CharField(blank=True, default='Not specified', max_length=100, null=True),
        ),
    ]
