# Generated by Django 5.1.7 on 2025-10-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_seekerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seekerrequest',
            name='messsage',
        ),
        migrations.AddField(
            model_name='seekerrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seekerrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
