# Generated by Django 5.2.4 on 2025-10-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_seekerrequest_messsage_seekerrequest_message_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seekerrequest',
            unique_together={('referral_post', 'requester')},
        ),
    ]
