# Generated by Django 5.2.4 on 2025-10-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_seekerrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='seekerrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
