# Generated by Django 5.2.4 on 2025-11-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_seekerrequest_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerrequest',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
