# Generated by Django 5.2.4 on 2025-11-15 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_googleauthuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleAuthUser',
        ),
    ]
