# Generated by Django 5.2.4 on 2025-11-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_random'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Random',
            new_name='Random1',
        ),
    ]
