"""
Django settings for Udyog project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os
from datetime import timedelta
import dj_database_url

 
# ----------------------------------------------------
# BASE DIRECTORY
# ----------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# ----------------------------------------------------
# STATIC FILES CONFIG (🔥 FIXED FOR CLOUD RUN)
# ----------------------------------------------------
STATIC_URL = '/static/'

# Folder that contains your frontend static source files
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Folder where collectstatic will dump files
STATIC_ROOT = BASE_DIR / "staticfiles"

# Serve static files using whitenoise
# Insert whitenoise after SecurityMiddleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # 🔥 REQUIRED
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Enable whitenoise optimized static file storage
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ----------------------------------------------------
# SECURITY + DEBUG
# ----------------------------------------------------
SECRET_KEY = os.environ.get("SECRET_KEY", "fallback-key")
DEBUG = os.environ.get("DEBUG", "FALSE").upper() == "TRUE"

ALLOWED_HOSTS = [
    'udyog-refer.onrender.com',
    'localhost',
    '127.0.0.1',
    'udyog-refer-89385722038.asia-south1.run.app',
    'udyog-refer-beta-89385722038.asia-south1.run.app',
    '.run.app',
    '*'
]


# ----------------------------------------------------
# APPLICATIONS
# ----------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'channels',
    'rest_framework',
]


# ----------------------------------------------------
# REST FRAMEWORK + JWT
# ----------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}


# ----------------------------------------------------
# URLS + TEMPLATES
# ----------------------------------------------------
ROOT_URLCONF = 'Udyog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Udyog.wsgi.application'
ASGI_APPLICATION = "Udyog.asgi.application"


# ----------------------------------------------------
# CHANNELS (WebSockets)
# ----------------------------------------------------
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


# ----------------------------------------------------
# DATABASE (ENV VAR DRIVEN — Cloud Run Ready)
# ----------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# ----------------------------------------------------
# AUTH + MEDIA
# ----------------------------------------------------
AUTH_USER_MODEL = 'home.User'
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ----------------------------------------------------
# PASSWORD VALIDATORS
# ----------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ----------------------------------------------------
# INTERNATIONALIZATION
# ----------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ----------------------------------------------------
# JWT CONFIG
# ----------------------------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=50),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# ----------------------------------------------------
# GOOGLE AUTH KEYS
# ----------------------------------------------------
GOOGLE_CLIENT_ID = "89385722038-m21hg6qe37os45ij3kg42k4u0ikt7fm3.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
